name: build-test-deploy
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: setup-repos
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: build
        run: |
          npm install
          npm run build

      - name: install-ssh-keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_SECRET_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          config: ${{ secrets.SSH_CONFIG }}

      - name: rsync-over-SSH
        run: rsync -av -e 'ssh -p 5555' dist/ psycho-kitty.fr:psycho-kitty.fr/
